import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import MobNavbar from "@/components/navbar/MobNavbar";
import Navbar from "@/components/navbar/Navbar";
import { Footer } from "@/components";
import Head from "next/head"; // Import Head component


const font = Heebo({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Type Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
      <Head>
        {/* Favicon ko set karte hain */}
        <link
          rel="icon"
          href="/images/favicon.ico"  // Favicon ka path
          type="image/ico"
          sizes="16x16"
        />
      </Head>
     
        <Navbar />
        <MobNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
